nodeLinker: node-modules
npmRegistries:
  //npm.pkg.github.com:
    npmAuthToken: ${GMO_NPM_TOKEN}
    npmAlwaysAuth: true
  //npm.pkg.github.com/GoMaxOne:
    npmAuthToken: ${GMO_NPM_TOKEN}
    npmAlwaysAuth: true
npmScopes:
  gomaxone:
    npmAuthToken: ${GMO_NPM_TOKEN}
    npmAlwaysAuth: true
    npmRegistryServer: "https://npm.pkg.github.com/GoMaxOne"

